name: Build & Publish docs

on:
  pull_request:
    paths:
      - ".github"
      - ".github/workflows/*-docs.yml"
  push:
    paths:
      - ".github"
      - ".github/workflows/*-docs.yml"
  workflow_dispatch:

jobs:
  build:
    name: Build & Publish docs

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"
          cache-dependency-path: "docs/package-lock.json"

      - name: Cache docusaurus
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/docs/.docusaurus
          key: |
            ${{ runner.os }}-docusaurus
          restore-keys: |
            ${{ runner.os }}-docusaurus

      - name: Install dependencies
        run: |
          npm ci --prefix docs

      - name: Lint / Formatting
        run: |
          npm run typecheck --prefix docs
          # TODO: should add more in the future if needed

      - name: Build
        run: |
          npm run build --prefix docs

      - name: Deploy
        if: github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && github.ref_name == 'main')
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build
